# Generated by Django 5.0.1 on 2024-02-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0002_alter_passager_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_client',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
