# Generated by Django 5.0.1 on 2024-02-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0005_alter_passager_categorie_alter_passager_daten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passager',
            name='id_passager',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
