# Generated by Django 5.0.1 on 2024-03-03 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0007_remove_vol_dated_trajet_distance_vol_datetimed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vol',
            name='datetimeD',
        ),
        migrations.AddField(
            model_name='vol',
            name='dateD',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vol',
            name='timeD',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
