# Generated by Django 5.0.1 on 2024-03-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsttry', '0008_remove_vol_datetimed_vol_dated_vol_timed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='idville',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
